### ISSUE TITLE
删除用户接口返回异常

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#11]
登陆admin账户
调用接口 http://172.24.5.149:12345/login
参数name = admin / password = 123456
step
1.调用删除接口http://172.24.5.149:12345/users/manzhao
预期结果 返回204
实际返回结果 
{
  "status": 500,
  "error": "Internal Server Error",
  "message": "nested exception is org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (com.baifendian.swordfish.dao.mapper.UserMapperProvider.delete).  Cause: org.apache.ibatis.binding.BindingException: Parameter 'arg0' not found. Available parameters are [name, param1]"
}
预期返回结果
Response:
Status: 204 No Content

**Comment by caojingwei** [comment]
已查明属于sql问题
