### ISSUE TITLE
新增用户接口返回提示信息不准确

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#12]
登陆admin账户
调用接口 http://172.24.5.149:12345/login 
参数name = admin / password = 123456
step
1.post请求接口 
 http://172.24.5.149:12345/users/guiyang090909
2.参数emai = guiyang.shi@baifendian.com，password = 123456,proxyUsers = ["hadoop","bdi"]
实际结果
{
  "status": 500,
  "error": "Internal Server Error",
  "message": "User has exist, can't create again."
}
预期结果 
此用户为被创建，只是邮箱已经被占用，应提示正确的返回结果信息

**Comment by caojingwei** [comment]
邮件或者用户名作为用户的唯一表示，如果被占用既可以代表该用户已经存在。
