### ISSUE TITLE
修改用户信息接口返回异常

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#13]
登陆guiyang账户
调用接口 http://172.24.5.149:12345/login
参数name = guiyang / password = 123456
step
1.patch接口 http://172.24.5.149:12345/users/guiyang (此用户为登陆用户）
2.参数规则（传什么参数 修改什么参数 另外用户自己无法修改proxyUsers信息）
3.传入参数email = guiyang.shi1234@baifendian.com ／desc = 修改邮箱和手机号码／phone = 18612681193  
4.send 发送请求
---------------------------------------------------------
实际结果
{
  "status": 500,
  "error": "Internal Server Error",
  "message": "Password \"null\" not valid"
}
---------------------------------------------------------
预期结果
传入参数信息被修改
---------------------------------------------------------
log片段信息
[INFO][901608530314696] 2017-05-15 14:32:21.747 com.baifendian.swordfish.webserver.controller.UserController:[92] - Operator user guiyang, modify user, name: guiyang, email: guiyang.shi123@baifendian.com, desc: 修改邮箱和增加电话号码, password: ******, phone: 18612681193, proxyUsers: null
[ERROR][901608530919109] 2017-05-15 14:32:21.748 com.baifendian.swordfish.webserver.exception.ControllerExceptionAdvice:[44] - controller catch some error
com.baifendian.swordfish.webserver.exception.ParameterException: Password "null" not valid
	at com.baifendian.swordfish.webserver.utils.ParamVerify.verifyPassword(ParamVerify.java:117)
	at com.baifendian.swordfish.webserver.service.UserService.modifyUser(UserService.java:139)
	at com.baifendian.swordfish.webserver.controller.UserController.modifyUser(UserController.java:95)
	at sun.reflect.GeneratedMethodAccessor629.invoke(Unknown Source)

**Comment by caojingwei** [comment]
待测试

**Comment by shiguiyang** [comment]
已修复
