### ISSUE TITLE
建议：创建项目接口（管理员账户创建返回结果信息确认）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#14]
登陆admin账户
调用接口 http://172.24.5.149:12345/login
参数name = admin / password = 123456
step
1.http://172.24.5.149:12345/projects/project_name0011111
预计结果
未知 请给出管理员账户创建返回结果信息
实际结果
  "status": 500,
  "error": "Internal Server Error",
  "message": "User \"admin\" is not admin"

**Comment by caojingwei** [comment]
信息已经更正
