### ISSUE TITLE
创建项目接口（重复创建时返回服务器异常信息）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#15]
登陆guiyang账户
调用接口 http://172.24.5.149:12345/login
参数name = guiyang / password = 123456
step
1.http://172.24.5.149:12345/projects/project_name01234
2.创建成功后再次点击
预计结果
失败，返回 Status: 4xx, 并包含错误信息 
实际结果
失败，返回 Status: 500, 并包含错误信息

**Comment by caojingwei** [comment]
不太理解这个问题？重复创建的时候服务器会返回异常信息。

**Comment by shiguiyang** [comment]
步骤
1.调用第一次接口-创建项目成功
2.调用第二次接口-此项目已存在
3.调用第三次接口-报错
报错信息如下
 "status": 500,
  "error": "Internal Server Error",
  "message": "nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='newProject.name', mode=IN, javaType=class java.lang.Object, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: No operations allowed after statement closed."

**Comment by caojingwei** [comment]
已经修复

**Comment by shiguiyang** [comment]
已经解决
