### ISSUE TITLE
查询项目下所有用户接口（返回结果异常）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#16]
登陆udp账户
调用post接口 http://172.24.5.149:12345/login
参数name = udp / password = 123123
调用查询项目get请求接口 http://172.24.5.149:12345/projects
查询有此项目project_name1111
step
1.调用post项目添加用户接口http://172.24.5.149:12345/projects/project_name1111/users/guiyangli
参数perm =4
2.添加成功后，调用查询项目下所有用户接口get请求http://172.24.5.149:12345/projects/project_name1111/users
预计结果
Response:
Status: 200 OK
[
  {
    "projectName": "project_name1111/",
    "userName": "guiyangli",
    "perm": 0x04,
    "createTime": 1468391778000,
    "modifyTime": 1468391778000,
    "owner": "udp"
  }
]
实际结果
 [
  {
    "projectName": "project_name1111",
    "userName": null,
    "perm": 4,
    "createTime": 1494838189000,
    "modifyTime": 1494838189000
  }
]

**Comment by caojingwei** [comment]
存在异常已经修复
