### ISSUE TITLE
项目修改一个用户接口（返回结果异常）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#17]
登陆udp账户
调用post接口 http://172.24.5.149:12345/login
参数name = udp / password = 123123
调用查询项目get请求接口 http://172.24.5.149:12345/projects
查询有此项目project_name1111
step
1.调用post项目添加用户接口http://172.24.5.149:12345/projects/project_name1111/users/guiyangli
参数perm =4
2.添加成功后，查看数据库project_user/project表确定用户和项目已经关联
3.调用put请求项目修改一个用户接口http://172.24.5.149:12345/projects/project_name1111/users/guiyangli
参数perm = 2
预计结果
Response:
Status: 200 OK
实际结果
 "status": 500,
  "error": "Internal Server Error",
  "message": "nested exception is org.apache.ibatis.binding.BindingException: Parameter 'projectId' not found. Available parameters are [param1, projectUser]"
}

**Comment by caojingwei** [comment]
数据库sql异常已经修改
