### ISSUE TITLE
修改项目接口（输出project没有的参数也可调用成功无报错信息）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#20]
登陆udp账户
调用post接口 http://172.24.5.149:12345/login
参数name = udp / password = 123123
调用查询项目get请求接口 http://172.24.5.149:12345/projects
查询有此项目udp
step
1.调用patch请求 修改项目接口http://172.24.5.149:12345/projects/udp
参数password = 123456
预计结果
请给做正确的返回信息和状态码。
实际结果
Response:
Status: 200 OK
 "name": "udp",
  "desc": "再次修改项目描述",
  "createTime": 1494380838000,
  "modifyTime": 1494841592001,
  "owner": "udp"

**Comment by caojingwei** [comment]
参数可选的，如果都不填写那么也是正常的，如果是可选，但是至少选择一项，那么是需要出异常的

**Comment by shiguiyang** [comment]
修改项目名  name参数也无法修改
