### ISSUE TITLE
新增资源接口状态码返回与文档不符

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#21]
登陆udp账户
调用post接口 http://172.24.5.149:12345/login
参数name = udp / password = 123123
调用查询项目get请求接口 http://172.24.5.149:12345/projects
查询有此项目udp
step
1.调用post请求 新增资源接口http://172.24.5.149:12345/projects/project_name1111/resources/project_name112111.txt
参数 file = 上传本地文件  /desc = 新增资源描述
预计结果
Response:
Status: 201 OK
 {
  "name": "project_name112111.txt",
  "desc": "测试路径",
  "createTime": 1494917808711,
  "modifyTime": 1494917808711,
  "projectName": "project_name1111",
  "owner": "udp",
  "suffix": "txt",
  "originFilename": "30361.txt"
}
实际结果
Response:
Status: 200 OK
 {
  "name": "project_name112111.txt",
  "desc": "测试路径",
  "createTime": 1494917808711,
  "modifyTime": 1494917808711,
  "projectName": "project_name1111",
  "owner": "udp",
  "suffix": "txt",
  "originFilename": "30361.txt"
}

**Comment by caojingwei** [comment]
返回码需要规范，待定
