### ISSUE TITLE
修改并创建资源接口（无法修改资源信息）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#22]
登陆udp账户
调用post接口 http://172.24.5.149:12345/login
参数name = udp / password = 123123
调用查询项目get请求接口 http://172.24.5.149:12345/projects
查询有此项目project_name1111
step
1.调用put请求 修改并创建资源接口http://172.24.5.149:12345/projects/project_name1111/resources/project_name.txt
参数 file = 要替换的txt文件  /desc =再次修改项目描述
预计结果
Response:
Status: 200 OK
实际结果
 "status": 500,
  "error": "Internal Server Error",
  "message": "nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='projectName', mode=IN, javaType=class java.lang.Object, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: No operations allowed after statement closed."
备注 只修改资源名称时 报400无返回meeage

**Comment by shiguiyang** [comment]
"status": 500,
  "error": "Internal Server Error",
  "message": "Error attempting to get column 'owner' from result set.  Cause: java.sql.SQLException: Invalid value for getInt() - 'udp'\n; SQL []; Invalid value for getInt() - 'udp'; nested exception is java.sql.SQLException: Invalid value for getInt() - 'udp'"

**Comment by caojingwei** [comment]
这个可能是149上数据库没有实时更新导致的，需要验证

**Comment by shiguiyang** [comment]
步骤
1.调用第一次接口-创建资源成功
2.调用第二次接口-此资源已存在
3.调用第三次接口-报错

**Comment by caojingwei** [comment]
修复

**Comment by shiguiyang** [comment]
已修复
