### ISSUE TITLE
下载资源接口（拷贝异常）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#23]
登陆udp账户
调用post接口 http://172.24.5.149:12345/login
参数name = udp / password = 123123
调用查询项目get请求接口 http://172.24.5.149:12345/projects
查询有此项目project_name1111并有资源project_name112111.txt
step
1.调用get请求 下载资源接口http://172.24.5.149:12345/projects/project_name1111/resources/project_name112111.txt/file
预计结果
Response:
Status: 200 OK
实际结果
{
  "status": 500,
  "error": "Internal Server Error",
  "message": "Copy exception"
}

**Comment by caojingwei** [comment]
修复，这是由于缓存文件夹没有自动生成造成的
