### ISSUE TITLE
建议：新增资源（没有权限新增／上传文件不存在）异常的返回结果希望可以给出

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#24]
没有异常处理的返回结果，请后续增加

**Comment by shiguiyang** [comment]
没有权限
现在返回状态码500 
文件不存在
 "timestamp": 1494922071951,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "java.lang.RuntimeException",
  "message": "java.lang.RuntimeException: java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms",
  "path": "/projects/project_name1111/resources/project_name112111.txt"

**Comment by caojingwei** [comment]
这个不是很看懂

**Comment by shiguiyang** [comment]
已不存在
