### ISSUE TITLE
删除资源接口（没做异常操作处理：删除不存在的资源）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#29]
陆udp账户
调用post接口 http://172.24.5.149:12345/login
参数name = udp / password = 123123
调用查询项目get请求接口 http://172.24.5.149:12345/projects
查询有此项目project_name1111
项目下没有资源project_name112321a1.jpg
step
1.调用delete请求 删除资源接口http://172.24.5.149:12345/projects/project_name1111/resources/project_name112321a1.jpg
预计结果
无法找到资源
实际结果
拷贝接口执行完成没有报错

**Comment by caojingwei** [comment]
未能复现此BUG

**Comment by shiguiyang** [comment]
已不存在
