### ISSUE TITLE
新增数据源接口（调用错误 复现概率3/10）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#32]
陆udp账户
调用post接口 http://172.24.5.149:12345/login
参数name = udp / password = 123123
调用查询项目get请求接口 http://172.24.5.149:12345/projects
查询有此项目project_name1111
项目下没有mysql数据源anAaewdatsuourea
step
1.调用post请新增数据源 http://172.24.5.149:12345/projects/project_name1111/datasources/anAaewdatsuourea
参数
type:MYSQL
parameter:{"address""jdbc:mysql://172.24.5.149:3306/","database":"SQL_0504","user":"swordfish","password":"swordfish"}
预计结果
Response:
Status: 201 Created
{
  "name": "bdi_db",
  "type": "MYSQL",
  "desc": "bdi 数据库",
  "parameter": {
      "address":"jdbc:mysql://172.18.1.22:3306",
      "database":"test",
      "user":"root",
      "password":"123456"
    }, 
  "createTime": 1468391778000,
  "modifyTime": 1468391778000,
  "projectName":"bdi",
  "owner": "bdi_user"
实际结果
 "status": 500,
  "error": "Internal Server Error",
  "message": "nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='dataSource.name', mode=IN, javaType=class java.lang.Object, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: No operations allowed after statement closed."

**Comment by caojingwei** [comment]
未能重现，已经进行过20次试验

**Comment by shiguiyang** [comment]
更新步骤
1.新增数据源成功后，再次调用此接口
2.第一次返回结果正确-》第二次出现此bug
复现率100% 
如有疑问可找测试人员帮忙复现

**Comment by caojingwei** [comment]
已经修复
