### ISSUE TITLE
查询项目下所有工作流接口没有实现

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#35]
该 API 不会返回工作流的配置详情。
GET /projects/:project-name/workflows

Response:
Status: 200 OK
[
  {
    "name": "bdi_base_workflow",
    "desc": "bdi基础数据加工工作流",
    "projectName": "bdi",
    "createTime": 1468391778000,
    "modifyTime": 1468391778000,
    "proxyUser": "bdi",
    "queue": "myqueue",
    "owner": "bdi_user",
    "extras": {...}
  }
]

**Comment by caojingwei** [comment]
路由配置不正确导致已经修复

**Comment by shiguiyang** [comment]
24日版本验证通过 已修复
