### ISSUE TITLE
查询工作流详情（工作流不存在的情况下依然查询成功）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#37]
登陆udp账户
调用post接口 http://172.24.5.149:12345/login
参数name = udp / password = 123123
调用查询项目get请求接口 http://172.24.5.149:12345/projects
查询有此项目project_name1111
项目下没有mysql数据源11project_name1111workflow
step
1.调用get查询工作流详情接口 http://172.24.5.149:12345/projects/project_name1111/workflows/11project_name1111workflow
预计结果
Response:
Status: 200 OK
[
  {
    "name": "bdi_base_workflow",
    "desc": "bdi基础数据加工工作流",
    "data": {
      ...
    },
    "projectName": "bdi",
    "createTime": 1468391778000,
    "modifyTime": 1468391778000,
    "proxyUser": "bdi",
    "queue": "myqueue",
    "owner": "bdi_user",
    "extras": {...}
  }
]
实际结果
 "status": 200,
  {}
备注 工作流不存在 请返回正确的执行结果和信息

**Comment by caojingwei** [comment]
已经修复

**Comment by shiguiyang** [comment]
验证通过
