### ISSUE TITLE
增加调度配置（默认timeout：秒 1800，实际18000）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#38]
登陆udp账户
调用post接口 http://172.24.5.149:12345/login
参数name = udp / password = 123123
调用查询项目get请求接口 http://172.24.5.149:12345/projects
查询有此项目project_name1111
项目下存在工作流project_name1112workflow
step
1.调用post新增调度配置 http://172.24.5.149:12345/projects/project_name1111/workflows/project_name1112workflow/schedules
参数
schedule:{"startDate": 1495512732,"endDate": 1495599132,"crontab":"0 8 * * * * ?"}
notifyType:SUCCESS
2.查看timeout参数返回值
预计结果
timeout  : 1800
实际结果
timeout  : 18000
备注 
timeout   类型（int）  描述  （单位: 秒, 默认为: 1800, 有效值 (0,43200]）

**Comment by caojingwei** [comment]
已经修复

**Comment by shiguiyang** [comment]
验证通过
