### ISSUE TITLE
调度（上线／下线）接口-log中有error（mysql报错）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#39]
调用post接口http://172.24.5.149:12345/projects/project_name1111/workflows/project_name1112workflow/schedules/offline
http://172.24.5.149:12345/projects/project_name1111/workflows/project_name1112workflow/schedules/online
返回结果正常
但log日志中有error
ERROR][1524634131378538] 2017-05-22 19:36:07.347 com.baifendian.swordfish.webserver.controller.ScheduleController:[186] - Schedule offline error
org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*
FROM schedules as s
JOIN project_flows as p_f on s.flow_id = p_f.id
JOIN proje' at line 1

**Comment by caojingwei** [comment]
已经修复

**Comment by shiguiyang** [comment]
上线接口此问题依然存在，下线接口已验证通过

**Comment by caojingwei** [comment]
上线接口的具体错误是什么？

**Comment by shiguiyang** [comment]
已修复
