### ISSUE TITLE
统计某天的分小时级别的任务运行状态（参数hour填写错误依然执行成功）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#43]
调用get请求执行“统计某天的分小时级别的任务运行状态”接口
http://172.24.5.149:12345/statistic/states-hour?projectName=project_name1111&date=3232ttr
上面接口data 参数填写错误 进行执行，依然可以执行成功

**Comment by caojingwei** [comment]
未能重现

**Comment by shiguiyang** [comment]
验证通过
