### ISSUE TITLE
查询任务运行情况(执行成功-返回值异常)

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#47]
调用get请求 查询任务运行情况接口
http://172.24.5.149:12345/executors?projectName=project_name1111&startDate=1495524607&endDate=1495526227

**Comment by shiguiyang** [comment]
"total": 0,
  "length": 100,
  "executions": []
}
返回结果异常 
stardate or enddate无论填写任何int型数字 都是返回此结果
execution_flows理由此调度任务运行记录

**Comment by caojingwei** [comment]
缺少workflowName参数，参考API
https://github.com/baifendian/swordfish/wiki/workflow-exec%26maintain

**Comment by shiguiyang** [comment]
已和开发人员确认，API文档workflowName不是必填项，估此问题依然存在

**Comment by caojingwei** [comment]
已经修复

**Comment by shiguiyang** [comment]
已修复
