### ISSUE TITLE
新增数据源接口（多次调用后报错）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#53]
1.调用post请新增数据源 http://172.24.5.149:12345/projects/project_name1111/datasources/aaanAaewdatsuourea
参数
type:MYSQL
parameter:{"address""jdbc:mysql://172.24.5.149:3306/","database":"SQL_0504","user":"swordfish","password":"swordfish"}
步骤
1，第一次调用新增成功
2，第二次调用返回此数据源已存在
3，再次调用次接口，报错
报错返回信息
 "status": 500,
  "error": "Internal Server Error",
  "message": "nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='dataSource.name', mode=IN, javaType=class java.lang.Object, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: No operations allowed after statement closed."

**Comment by caojingwei** [comment]
已经修复

**Comment by shiguiyang** [comment]
已经修复
