### ISSUE TITLE
拷贝资源接口返回字段（projectname/owner为null）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#54]
step
1.调用post请求 拷贝资源接口http://172.24.5.149:12345/projects/project_name1111/resource-copy
srcResName:project_nameaoo.txt
destResName:project_name.txt
desc:同项目资源拷贝
实际结果
  "name": "project_name.txt",
  "desc": "备注",
  "createTime": 1494919685000,
  "modifyTime": 1495703698980,
  "projectName": null,
  "owner": null,
  "suffix": "txt",
  "originFilename": "1111111.txt"
}
备注 owner/projectName 2个字段为空

**Comment by caojingwei** [comment]
已经修复

**Comment by shiguiyang** [comment]
已修复
