### ISSUE TITLE
删除用户接口报错

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#56]
登陆udp用户
调用delete接口 
http://172.24.5.149:12345/users/guiyang.shijian
报错信息如下

  "status": 500,
  "error": "Internal Server Error",
  "message": "nested exception is org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (com.baifendian.swordfish.dao.mapper.UserMapperProvider.delete).  Cause: org.apache.ibatis.binding.BindingException: Parameter 'arg0' not found. Available parameters are [name, param1]"
}
log信息如下
[ERROR][2371531068656449] 2017-06-01 14:51:04.286 com.baifendian.swordfish.webserver.exception.ControllerExceptionAdvice:[129] - controller catch some error
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (com.baifendian.swordfish.dao.mapper.UserMapperProvider.delete).  Cause: org.apache.ibatis.binding.BindingException: Parameter 'arg0' not found. Available parameters are [name, param1]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy68.delete(Unknown Source)

**Comment by caojingwei** [comment]
已经修复

**Comment by shiguiyang** [comment]
此问题已修复
