### ISSUE TITLE
新增用户接口异常

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#57]
登陆admin账户
调用post新增接口
http://172.24.5.149:12345/users/guiyasdfsdfasdfasdf
参数
email:guiyang.shijian11d2121@baifendian.com
desc:bdi 用户
password:1234567
proxyUsers:["hado2op","bdi"]
报错信息如下
{
  "status": 500,
  "error": "Internal Server Error",
  "message": "nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='user.name', mode=IN, javaType=class java.lang.Object, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: No operations allowed after statement closed."
}

**Comment by caojingwei** [comment]
已经修复

**Comment by shiguiyang** [comment]
已修复
