### ISSUE TITLE
查询一个项目下所有调度配置

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#59]
登陆udp账户
调用get接口
http://172.24.5.149:12345/projects/project_name1111/workflows/schedules
返回字段
[
  {
    "projectName": null,
    "workflowName": null,
    "desc": null,
    "notifyType": "SUCCESS",
    "notifyMails": [],
    "maxTryTimes": 1,
    "failurePolicyType": "END",
    "depWorkflows": [],
    "depPolicyType": "NO_DEP_PRE",
    "timeout": 1800,
    "createTime": 1495691998000,
    "modifyTime": 1495691998000,
    "owner": "udp",
    "scheduleParam": {
      "startDate": 1495512000,
      "endDate": 1495599000,
      "crontab": "0 8 * * * * ?"
    },
    "scheduleStatus": 0
  },
  {
    "projectName": null,
    "workflowName": null,
    "desc": null,
    "notifyType": "SUCCESS",
    "notifyMails": [],
    "maxTryTimes": 1,
    "failurePolicyType": "END",
    "depWorkflows": [],
    "depPolicyType": "NO_DEP_PRE",
    "timeout": 18000,
    "createTime": 1495452718000,
    "modifyTime": 1495452718000,
    "owner": "udp",
    "scheduleParam": {
      "startDate": 1495512000,
      "endDate": 1495599000,
      "crontab": "0 8 * * * * ?"
    },
    "scheduleStatus": 0
  }
]

缺少projectName／workflowName／depWorkflows／notifyMails／desc字段返回结果

**Comment by caojingwei** [comment]
depWorkflows，notifyMails有返回结果,[]就是返回结果，projectName desc workflowName无结果的BUG已经修复

**Comment by shiguiyang** [comment]
已修复
