### ISSUE TITLE
重复调用“修改并创建资源”接口，sql报错

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#62]
登陆udp账户
调用post接口 http://172.24.5.149:12345/login
参数name = udp / password = 123123
调用查询项目get请求接口 http://172.24.5.149:12345/projects
查询有此项目project_name1111
step
1.调用put请求 修改并创建资源接口http://172.24.5.149:12345/projects/project_name1111/resources/project_name.txt
参数 file = 要替换的txt文件 /desc =再次修改项目描述
重复调用后
{
  "status": 500,
  "error": "Internal Server Error",
  "message": "Error attempting to get column 'project_name' from result set.  Cause: java.sql.SQLException: Invalid value for getInt() - 'project_name1111'\n; SQL []; Invalid value for getInt() - 'project_name1111'; nested exception is java.sql.SQLException: Invalid value for getInt() - 'project_name1111'"
}

**Comment by caojingwei** [comment]
已经修复

**Comment by shiguiyang** [comment]
已修复 关闭
