### ISSUE TITLE
查询任务运行情况接口，统计信息字段 返回结果错误

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#63]
http://172.24.5.149:12345/executors?projectName=cszh02_pro02&startDate=1496643600000&endDate= 1496643600000
返回结果，统计信息字段，返回结果为0
{
  "total": 0,
  "from": 0,
  "executions": [
    {
      "execId": 1541,
      "projectName": "cszh02_pro02",
      "workflowName": "pub_cs04_spark_wf",
      "execType": "SCHEDULER",
      "submitTime": 1496643600000,
      "startTime": 1496643600000,
      "endTime": 1496643623000,
      "duration": 23,
      "submitUser": "udp",
      "proxyUser": "cs04",
      "queue": "ml",
      "status": 4,
      "owner": "udp",
      "extras": {
        "canvas": {
          "x": 0,
          "y": 0,
          "scale": 1
        },
        "flowType": "SHORT",
        "edges": [],
        "flowNodes": []
      }
    }
  ]
}

**Comment by shiguiyang** [comment]
与开发确认，开始／结束时间为同一时间段，会导致此bug，已修复，下个版本验证

**Comment by caojingwei** [comment]
已经修复

**Comment by shiguiyang** [comment]
已修复 关闭此issue
