### ISSUE TITLE
创建／修改流任务-"notifyType"字段设置为None时 400报错   

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#66]
SUCCESS-成功发，FAILURE-失败发，ALL-成功或失败都发，NONE-都不发, 注意大小写不敏感, 默认是 None
创建或修改流任务接口
设置notifytype接口时 设置字段值为None时 400报错  
调用put/post
http://172.24.5.149:12345/projects/project_name1111/streaming/project_name111workflow
参数
desc:创建新的流任务
type:SPARK_STREAMING
parameter:{"mainClass":"org.apache.spark.examples.streaming.KafkaWordCount","mainJar":{"scope":"PROJECT","res":"pub_real_flow0608.jar"},"args":"172.24.5.149:2181 cstopic01","files":[],"archives":[],"libJars":[],"deployMode":"CLUSTER","driverMemory":"512M","driverCores":1,"numExecutors":1,"executorMemory":"512M","executorCores":1}
userDefParams:[{"prop":"a1","value":"2"}]
notifyType:None
notifyMails:["guiyang.shi@baifendian.com"]

**Comment by caojingwei** [comment]
所有的枚举类型，都是大小写敏感的，如果没有特殊说明，所有的枚举默认全大写。这是文档错误，更正一下
